language: python
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27-cdh
    - python: 2.7
      env: TOX_ENV=py27-hdp
    - python: 3.6
      env: TOX_ENV=py36-cdh
    - python: 3.6
      env: TOX_ENV=py36-hdp
  allow_failures:
  - python: 3.6
jdk: oraclejdk7
branches:
  except:
    - gh-pages
install:
  - pip install tox
script:
  - tox --version
  - python setup.py test --tox-args="-e $TOX_ENV"
